# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

# Additional rules, not enabled by default
linter:
  rules:
    - prefer_double_quotes
