name: cubik
description: "Yet another web game!"

# Prevent accidental publishing to pub.dev
publish_to: "none"

version: 2.0.0+5

environment:
  sdk: ">=3.2.5"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: 10.0.0
  flutter_bloc: 9.1.1
  path_provider: 2.1.5
  flutter_animate: 4.5.2
  equatable: 2.0.7
  go_router: 15.2.4
  image_picker: 1.1.2
  fl_chart: 1.0.0
  cupertino_icons: 1.0.8
  confetti: 0.8.0
  share_plus: 11.0.0
  url_launcher: 6.3.1
  simple_icons: 14.6.1
  logger: 2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 10.0.0
  mocktail: 1.0.4
  flutter_lints: 6.0.0
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.6
  husky: 0.1.7

flutter:
  uses-material-design: true

  # Needed for the generation of localized strings from arb files
  generate: true

  assets:
    - assets/
