name: lint

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --no-cli-animations
      - name: Install dependencies
        run: flutter pub get
      - name: Run check
        run: flutter analyze && dart format -o none --set-exit-if-changed .
