name: lint

on:
  push:
  pull_request:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: vhanda/flutter-build-runner-action@v1
      - name: Run Flutter linter
        run: flutter analyze
