name: merge

on:
  pull_request:
    types: [opened, edited]

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --no-cli-animations
      - name: Install dependencies
        run: flutter pub get
      - name: Run commitlint on PR title
        run: echo "${{ github.event.pull_request.title }}" | dart run commitlint_cli
