name: test

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --no-cli-animations
      - name: Run Flutter tests
        run: flutter test
