name: test

on:
  push:
  pull_request:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Run Flutter tests
        run: flutter analyze
